env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - 4
  no-console: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "**/*.test.js"
        - "**/*.spec.js"
        - "**/*set_up.js"
        - "**/*teardown.js"
        - "**/*_test.js"
  # for test files that include 'should' or 'expect'
  no-unused-expressions:
    - error
    - allowShortCircuit: true
    - allowTernary: true
    - allowTaggedTemplates: true
