services:
  database:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./sre_practice.sql:/docker-entrypoint-initdb.d/sre_practice.sql
      - ./sre_practice_test.sql:/docker-entrypoint-initdb.d/sre_practice_test.sql
      #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_DATABASE: ${DB_NAME}
volumes:
  db-volume:
    driver: local
